export const faqs = [
    {
        id: 0,
        question: "Little interest or pleasure in doing things?",
        option1: "Not at all.",
        option2: "Several days.",
        option3: "More than half the days.",
        option4: "Nearly every day.",
    },
    {
        id: 1,
        question: "Feeling down, depressed, or hopeless?",
        option1: "Not at all.",
        option2: "Several days.",
        option3: "More than half the days.",
        option4: "Nearly every day.",
    },
    {
        id: 2,
        question: "Trouble falling or staying asleep, or sleeping too much?",
        option1: "Not at all.",
        option2: "Several days.",
        option3: "More than half the days.",
        option4: "Nearly every day.",
    },
    {
        id: 3,
        question: "Feeling tired or having little energy?",
        option1: "Not at all.",
        option2: "Several days.",
        option3: "More than half the days.",
        option4: "Nearly every day.",
    },
    {
        id: 4,
        question: "Poor appetite or overeating?",
        option1: "Not at all.",
        option2: "Several days.",
        option3: "More than half the days.",
        option4: "Nearly every day.",
    },
];
